import { Conversation } from '../types';

export interface DownloadOptions {
  format: 'pdf' | 'markdown';
  mode: 'exact' | 'balanced' | 'aggressive';
  conversation: Conversation | string | null;
  compressed?: {
    full?: Conversation;
    balanced?: Conversation;
    aggressive?: string;
  };
}

const escapeHTML = (text: string): string => {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
};

const downloadFile = (content: string, filename: string, mimeType: string): void => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const resolveMessages = (
  conversation: Conversation | string | null,
  mode: DownloadOptions['mode'],
  compressed: DownloadOptions['compressed']
): { messages: Conversation['messages']; conv: Conversation | null } => {
  if (!conversation || typeof conversation === 'string') return { messages: [], conv: null };

  if (mode === 'aggressive') return { messages: [], conv: conversation };
  if (mode === 'balanced' && compressed?.balanced)
    return { messages: compressed.balanced.messages, conv: conversation };
  return { messages: conversation.messages ?? [], conv: conversation };
};

export const generateMarkdown = (
  conversation: Conversation | string | null,
  mode: DownloadOptions['mode'],
  compressed?: DownloadOptions['compressed']
): string => {
  if (!conversation) return '# Error\nNo conversation data available.';
  if (typeof conversation === 'string') return conversation;

  if (mode === 'aggressive' && compressed?.aggressive) return compressed.aggressive;

  const { messages, conv } = resolveMessages(conversation, mode, compressed);
  if (!conv) return '# Error\nNo conversation data.';

  let md = `# ${conv.title ?? 'Conversation Export'}\n\n`;
  md += `**Platform:** ${conv.platform}  \n`;
  md += `**Exported:** ${new Date(conv.exportedAt).toLocaleString()}  \n`;
  md += `**Mode:** ${mode}  \n`;
  md += `**Messages:** ${messages.length}\n\n---\n\n`;

  for (const msg of messages) {
    const role = msg.role === 'user' ? '👤 User' : '🤖 Assistant';
    md += `### ${role}\n\n${msg.content}\n\n---\n\n`;
  }

  md += `*Generated by AI Context Bridge*\n`;
  return md;
};

export const generateHTML = (
  conversation: Conversation | string | null,
  mode: DownloadOptions['mode'],
  compressed?: DownloadOptions['compressed']
): string => {
  if (!conversation) return '<h1>Error</h1><p>No conversation data available.</p>';

  if (typeof conversation === 'string') {
    return `<pre style="white-space:pre-wrap;font-family:sans-serif;line-height:1.6">${escapeHTML(conversation)}</pre>`;
  }

  if (mode === 'aggressive' && compressed?.aggressive) {
    return `<h1>${escapeHTML(conversation.title ?? 'Summary')}</h1><pre style="white-space:pre-wrap;font-family:sans-serif;line-height:1.6">${escapeHTML(compressed.aggressive)}</pre>`;
  }

  const { messages, conv } = resolveMessages(conversation, mode, compressed);
  if (!conv) return '<h1>Error</h1><p>No conversation data.</p>';

  let html = `<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>${escapeHTML(conv.title ?? 'Conversation')}</title>
<style>
  body{font-family:system-ui,sans-serif;line-height:1.6;color:#333;max-width:900px;margin:0 auto;padding:20px}
  h1{border-bottom:3px solid #007bff;padding-bottom:10px;color:#007bff}
  .meta{background:#f5f5f5;padding:15px;border-radius:5px;margin:20px 0;font-size:14px}
  .msg{margin:20px 0;padding:15px;border-radius:4px}
  .user{border-left:4px solid #28a745;background:#f0f8f5}
  .assistant{border-left:4px solid #007bff;background:#f0f5ff}
  .role{font-weight:bold;font-size:12px;text-transform:uppercase;margin-bottom:8px;color:#555}
  .content{white-space:pre-wrap;word-wrap:break-word}
  .footer{margin-top:40px;padding-top:20px;border-top:1px solid #eee;font-size:12px;color:#999;text-align:center}
</style></head><body>
<h1>${escapeHTML(conv.title ?? 'Conversation Export')}</h1>
<div class="meta">
  <p><strong>Platform:</strong> ${escapeHTML(conv.platform)}</p>
  <p><strong>Exported:</strong> ${new Date(conv.exportedAt).toLocaleString()}</p>
  <p><strong>Messages:</strong> ${messages.length}</p>
</div>`;

  for (const msg of messages) {
    const roleClass = msg.role === 'user' ? 'user' : 'assistant';
    const roleLabel = msg.role === 'user' ? '👤 User' : '🤖 Assistant';
    html += `<div class="msg ${roleClass}">
  <div class="role">${roleLabel}</div>
  <div class="content">${escapeHTML(msg.content)}</div>
</div>`;
  }

  html += `<div class="footer">Generated by AI Context Bridge &middot; ${new Date().toLocaleString()}</div>
</body></html>`;

  return html;
};

export const handleDownload = async (options: DownloadOptions): Promise<void> => {
  const { format, mode, conversation, compressed } = options;

  if (!conversation) throw new Error('No conversation to download');

  const timestamp = Date.now();

  if (format === 'markdown') {
    const content = generateMarkdown(conversation, mode, compressed);
    downloadFile(content, `conversation_${mode}_${timestamp}.md`, 'text/markdown');
    return;
  }

  if (format === 'pdf') {
    const html = generateHTML(conversation, mode, compressed);
    const html2pdf = (window as Window & { html2pdf?: unknown }).html2pdf;

    if (typeof html2pdf !== 'function') {
      throw new Error('PDF library not available. Try Markdown instead.');
    }

    await (html2pdf as (content: string, opts: object) => { save: () => void })(html, {
      margin: 10,
      filename: `conversation_${mode}_${timestamp}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { orientation: 'portrait', unit: 'mm', format: 'a4' },
    });
  }
};
