import { Conversation } from '../types';

export interface DownloadOptions {
  format: 'pdf' | 'markdown';
  mode: 'exact' | 'balanced' | 'aggressive';
  conversation: Conversation | null;
  compressed?: any;
}

// Generate Markdown content based on mode
export const generateMarkdown = (
  conversation: Conversation | string | null,
  mode: 'exact' | 'balanced' | 'aggressive',
  compressed?: any
): string => {
  if (!conversation) {
    return '# Error\nNo conversation data available.';
  }

  let messages = [];

  // Determine which version to use
  if (typeof conversation === 'string') {
    return conversation;
  }

  if (mode === 'exact') {
    messages = conversation.messages || [];
  } else if (mode === 'balanced' && compressed?.balanced) {
    messages = compressed.balanced.messages || [];
  } else if (mode === 'aggressive' && compressed?.aggressive) {
    return compressed.aggressive;
  } else {
    messages = conversation.messages || [];
  }

  let markdown = '';

  // Header
  markdown += `# ${conversation.title || 'Conversation Export'}\n\n`;
  markdown += `**Platform:** ${conversation.platform || 'Unknown'}\n`;
  markdown += `**Exported:** ${conversation.exportedAt}\n`;
  markdown += `**Mode:** ${mode.charAt(0).toUpperCase() + mode.slice(1)}\n`;
  markdown += `**Messages:** ${messages.length}\n\n`;

  if (conversation.metadata) {
    markdown += `## Metadata\n\n`;
    if (conversation.metadata.totalTokens) {
      markdown += `- **Tokens:** ${conversation.metadata.totalTokens}\n`;
    }
    if (conversation.metadata.characterCount) {
      markdown += `- **Characters:** ${conversation.metadata.characterCount}\n`;
    }
    if (conversation.metadata.codeBlockCount) {
      markdown += `- **Code Blocks:** ${conversation.metadata.codeBlockCount}\n`;
    }
    markdown += `\n`;
  }

  // Messages
  markdown += `## Conversation\n\n`;

  for (const message of messages) {
    const role = message.role === 'user' ? '👤 User' : '🤖 Assistant';
    markdown += `### ${role}\n\n`;
    markdown += `${message.content}\n\n`;

    if (message.metadata?.codeBlocks && message.metadata.codeBlocks.length > 0) {
      markdown += `#### Code Blocks\n\n`;
      message.metadata.codeBlocks.forEach((block: any) => {
        const language = block.language || 'code';
        markdown += `\`\`\`${language}\n${block.code}\n\`\`\`\n\n`;
      });
    }

    markdown += `---\n\n`;
  }

  // Footer
  markdown += `\n*Generated by AI Context Bridge*\n`;

  return markdown;
};

// Generate HTML content for PDF
export const generateHTML = (
  conversation: Conversation | string | null,
  mode: 'exact' | 'balanced' | 'aggressive',
  compressed?: any
): string => {
  if (!conversation) {
    return '<h1>Error</h1><p>No conversation data available.</p>';
  }

  let messages = [];
  let convData: Conversation | null = null;

  // Determine which version to use
  if (typeof conversation === 'string') {
    return `<h1>Conversation Summary</h1><pre style="white-space: pre-wrap; word-wrap: break-word;">${escapeHTML(conversation)}</pre>`;
  }

  convData = conversation;
  if (mode === 'exact') {
    messages = conversation.messages || [];
  } else if (mode === 'balanced' && compressed?.balanced) {
    messages = compressed.balanced.messages || [];
  } else if (mode === 'aggressive' && compressed?.aggressive) {
    return `<h1>${convData.title || 'Conversation Summary'}</h1><pre style="white-space: pre-wrap; word-wrap: break-word; font-family: Arial, sans-serif; line-height: 1.6;">${escapeHTML(compressed.aggressive)}</pre>`;
  } else {
    messages = conversation.messages || [];
  }

  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${escapeHTML(conversation.title || 'Conversation')}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #fff;
      margin: 0;
      padding: 20px;
      max-width: 900px;
      margin: 0 auto;
    }
    h1 {
      border-bottom: 3px solid #007bff;
      padding-bottom: 10px;
      color: #007bff;
    }
    h2 {
      border-bottom: 2px solid #e0e0e0;
      padding-bottom: 5px;
      color: #333;
      margin-top: 30px;
    }
    .metadata {
      background: #f5f5f5;
      padding: 15px;
      border-radius: 5px;
      margin: 20px 0;
      font-size: 14px;
    }
    .metadata p {
      margin: 5px 0;
    }
    .message {
      margin: 20px 0;
      padding: 15px;
      border-left: 4px solid #007bff;
      background: #f9f9f9;
    }
    .message.user {
      border-left-color: #28a745;
      background: #f0f8f5;
    }
    .message.assistant {
      border-left-color: #007bff;
      background: #f0f5ff;
    }
    .message-role {
      font-weight: bold;
      color: #555;
      font-size: 12px;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    .message-content {
      color: #333;
      white-space: pre-wrap;
      word-wrap: break-word;
    }
    .code-block {
      background: #2d2d2d;
      color: #f8f8f2;
      padding: 12px;
      border-radius: 5px;
      overflow-x: auto;
      font-family: 'Courier New', monospace;
      font-size: 12px;
      margin: 10px 0;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e0e0e0;
      font-size: 12px;
      color: #999;
      text-align: center;
    }
    .mode-badge {
      display: inline-block;
      padding: 4px 8px;
      background: #007bff;
      color: white;
      border-radius: 3px;
      font-size: 12px;
      margin-left: 10px;
    }
  </style>
</head>
<body>
  <h1>${escapeHTML(convData.title || 'Conversation Export')}<span class="mode-badge">${mode.toUpperCase()}</span></h1>

  <div class="metadata">
    <p><strong>Platform:</strong> ${escapeHTML(convData.platform || 'Unknown')}</p>
    <p><strong>Exported:</strong> ${new Date(convData.exportedAt).toLocaleString()}</p>
    <p><strong>Messages:</strong> ${messages.length}</p>
    ${convData.metadata?.totalTokens ? `<p><strong>Tokens:</strong> ${convData.metadata.totalTokens}</p>` : ''}
    ${convData.metadata?.characterCount ? `<p><strong>Characters:</strong> ${convData.metadata.characterCount}</p>` : ''}
    ${convData.metadata?.codeBlockCount ? `<p><strong>Code Blocks:</strong> ${convData.metadata.codeBlockCount}</p>` : ''}
  </div>

  <h2>Conversation</h2>
`;

  for (const message of messages) {
    const roleClass = message.role === 'user' ? 'user' : 'assistant';
    const roleDisplay = message.role === 'user' ? '👤 User' : '🤖 Assistant';

    html += `
  <div class="message ${roleClass}">
    <div class="message-role">${roleDisplay}</div>
    <div class="message-content">${escapeHTML(message.content)}</div>
`;

    if (message.metadata?.codeBlocks && message.metadata.codeBlocks.length > 0) {
      message.metadata.codeBlocks.forEach((block: any) => {
        const language = block.language || 'code';
        html += `<div class="code-block"><strong>${language}</strong>\n${escapeHTML(block.code)}</div>`;
      });
    }

    html += `  </div>\n`;
  }

  html += `
  <div class="footer">
    <p>Generated by AI Context Bridge | ${new Date().toLocaleString()}</p>
  </div>
</body>
</html>
`;

  return html;
};

// Helper function to escape HTML
const escapeHTML = (text: string): string => {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
};

// Download file helper
export const downloadFile = (content: string, filename: string, mimeType: string): void => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// Main download handler
export const handleDownload = async (options: DownloadOptions): Promise<void> => {
  const { format, mode, conversation, compressed } = options;

  if (!conversation) {
    throw new Error('No conversation to download');
  }

  try {
    if (format === 'markdown') {
      const markdown = generateMarkdown(conversation, mode, compressed);
      const filename = `conversation_${mode}_${Date.now()}.md`;
      downloadFile(markdown, filename, 'text/markdown');
    } else if (format === 'pdf') {
      const html = generateHTML(conversation, mode, compressed);
      const filename = `conversation_${mode}_${Date.now()}.pdf`;

      // Use html2pdf if available
      const html2pdf = (window as any).html2pdf;
      if (html2pdf) {
        const options = {
          margin: 10,
          filename: filename,
          image: { type: 'jpeg', quality: 0.98 },
          html2canvas: { scale: 2 },
          jsPDF: { orientation: 'portrait', unit: 'mm', format: 'a4' },
        };
        html2pdf().set(options).from(html).save();
      } else {
        throw new Error('PDF generation library not loaded. Using fallback.');
      }
    }
  } catch (error) {
    throw error;
  }
};
